# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Kafka properties.
spring:
  kafka:
    bootstrap-servers:
    - 3.39.237.221:9092
    template:
      default-topic: tacocloud_orders
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer